"""add date_taken to appointments

Revision ID: 12bbd29ff6fb
Revises: 842dd8a5609c
Create Date: 2026-08-03 16:12:26.672835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12bbd29ff6fb'
down_revision: Union[str, Sequence[str], None] = '842dd8a5609c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('date_taken', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'date_taken')
    # ### end Alembic commands ###
