"""add columns to  appointments

Revision ID: 3f1ebc805ea4
Revises: 493f1a2c4e86
Create Date: 2026-09-04 14:55:38.128839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1ebc805ea4'
down_revision: Union[str, Sequence[str], None] = '493f1a2c4e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('guest_name', sa.String(length=50), nullable=True))
    op.add_column('appointments', sa.Column('guest_email', sa.String(length=120), nullable=True))
    op.add_column('appointments', sa.Column('guest_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'guest_phone')
    op.drop_column('appointments', 'guest_email')
    op.drop_column('appointments', 'guest_name')
    # ### end Alembic commands ###
