"""add guest_token to appointments

Revision ID: 519f207f2e96
Revises: 980c6fe2a2fc
Create Date: 2026-08-27 11:17:04.858035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519f207f2e96'
down_revision: Union[str, Sequence[str], None] = '980c6fe2a2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('guest_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'appointments', ['guest_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='unique')
    op.drop_column('appointments', 'guest_token')
    # ### end Alembic commands ###
