"""add missing columns to services table

Revision ID: 650703f4e332
Revises: 4bec5acd4273
Create Date: 2026-08-15 11:16:06.375564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650703f4e332'
down_revision: Union[str, Sequence[str], None] = '4bec5acd4273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('duration', sa.Integer(), nullable=False))
    op.alter_column('services', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('services', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('services', 'price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('services', 'duration')
    # ### end Alembic commands ###
