"""add start_time and end_time to appointments

Revision ID: 980c6fe2a2fc
Revises: 79751ab19c5f
Create Date: 2026-08-24 12:16:37.761171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '980c6fe2a2fc'
down_revision: Union[str, Sequence[str], None] = '79751ab19c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('appointments', sa.Column('end_time', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('appointments', 'date_taken')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('date_taken', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'end_time')
    op.drop_column('appointments', 'start_time')
    # ### end Alembic commands ###
