"""add user_id to services

Revision ID: fd95c3979cbd
Revises: 12bbd29ff6fb
Create Date: 2026-08-09 18:06:56.784461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd95c3979cbd'
down_revision: Union[str, Sequence[str], None] = '12bbd29ff6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('services_name_key'), 'services', type_='unique')
    op.create_foreign_key(None, 'services', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_unique_constraint(op.f('services_name_key'), 'services', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('services', 'user_id')
    # ### end Alembic commands ###
